version: '3'
services:
  database:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'prisma'
    expose:
      - '5432'
    ports:
      - '2345:5432'

  build-watch:
    build: .
    command: yarn build:watch
    volumes:
      - .:/app

  codegen-watch:
    build: .
    command: yarn codegen:watch
    volumes:
      - .:/app

  gateway:
    build: .
    command: yarn workspace @services/gateway run dev
    volumes:
      - .:/app
    ports:
      - '4000:4000'

  products:
    build: .
    command: yarn workspace @services/products run dev
    environment:
      JWT_SECRET: 'secret'
    volumes:
      - .:/app
    expose:
      - '4000'

  users:
    build: .
    command: yarn workspace @services/users run dev
    environment:
      JWT_SECRET: 'secret'
    volumes:
      - .:/app
    expose:
      - '4000'
